Updated github actions

diff --git a/.github/workflows/pr_build_check.yml b/.github/workflows/pr_build_check.yml
--- a/.github/workflows/pr_build_check.yml
+++ b/.github/workflows/pr_build_check.yml
@@ -12,19 +12,24 @@ jobs:
         run: |
           git remote set-branches --add origin main
           git fetch
-          git diff --name-only origin/main
-          echo "changed_files=$(git diff --name-only origin/main | grep 'main.tex$')" >> $GITHUB_OUTPUT
+          changed_files=$(git diff --name-only origin/main | grep 'main.tex$') || true
+          if [ $(echo "$changed_files" | wc -l) -gt 1 ]; then
+            echo "::error::You are supposed to modify one document per branch"
+            exit 1
+          elif [ -n $changed_files ]; then 
+            echo "No document was modified"
+          fi
+          echo "file=$changed_files" >> $GITHUB_OUTPUT
       - name : Install dependencies
         run: |
-          sudo apt install -y \
-          texlive \
-          texlive-latex-extra \
-          texlive-lang-italian \
+          if [ -n "${{ steps.find.outputs.file }}" ]; then
+            sudo apt install -y texlive texlive-latex-extra texlive-lang-italian
+          fi
       - name: Compile the modified LaTeX file
         run: |
-          if [ -n "${{ steps.find.outputs.changed_files }}" ]; then
-            directory=$(dirname "${{ steps.find.outputs.changed_files }}")
-            file=$(basename "${{ steps.find.outputs.changed_files }}")
+          if [ -n "${{ steps.find.outputs.file }}" ]; then
+            directory=$(dirname "${{ steps.find.outputs.file }}")
+            file=$(basename "${{ steps.find.outputs.file }}")
             cd "$directory"
             pdflatex "$file"        
           fi
